Beer.create(name: "Budweiser", cost: 5, color: "Yellow", origin: "USA")
Beer.create(name: "Blue Point", cost: 6, color: "Orange", origin: "USA")
Beer.create(name: "Becks", cost: 5, color: "Amber", origin: "Germany")
Beer.create(name: "Rouge", cost: 7, color: "Brown", origin: "USA")
Beer.create(name: "Modelo", cost: 4, color: "Yellow", origin: "Mexico")
Beer.create(name: "Leffe", cost: 6, color: "Orange", origin: "Belgium")

Patron.create(name: "Billy Dale")
Patron.create(name: "John Smith")
Patron.create(name: "Chris Kringle")
Patron.create(name: "Johnny Stocks")

Type.create(name: "Pilsner", body: "Light")
Type.create(name: "IPA", body: "Medium")
Type.create(name: "Stout", body: "Full")
Type.create(name: "Ale", body: "Medium")
